### ISSUE TITLE
sshd does not start on Fedora >=30

### ISSUE THREAD

**Issue by aither64** [vpsfreecz/vpsadminos-image-build-scripts#39]
sshd sometimes does not start on boot on Fedora 30, even though it is enabled. It happens while testing built images and on staging as well. No idea what's going on, there's not even any attempt at starting it, the service is sometimes just ignored.

**Comment by GoodMirek** [comment]
I was original reporter of this issue in [Redmine](https://redmine.vpsfree.cz/issues/169#change-358). Let me add some more details here.
>> It happened again with #13892 and #13894, here is the reproduction scenario:
>> 1. Create a new VPS from FC30 template
>> 2. Deploy a public key
>> 3. Verify it is possible to login via SSH
>> 4. Enable Docker and FUSE features
>> 5. After automatic VPS restart, verify that it is not possible to login
>> 6. Initiate VPS restart
>> 7. Verify that it is not possible to login via SSH
>> 8. Generate a root passoword and login from VPS admin via console
>> 9. Verify that sshd is not running with command systemctl status sshd
>> 10. Run systemctl enable sshd and systemctl start sshd
>> 11. Verify that is is possible to login via SSH
>> 12. Initiate VPS restart
>> 13. Verify that is is possible to login via SSH

> \# 5 Updated by Aither 5 days ago
> Comment
> Yeah it happens regularly on F30. SSHD just doesn't start sometimes and I have no idea why. It is >enabled, but systemd ignores it for some reason. The steps don't matter, every VPS start is like a
> lottery ticket.

In two tests, I was able to reproduce that the issue happened only with additional VM features.

**Comment by aither64** [comment]
I don't think it's connected to any VM features. Just had the same thing happen on Fedora 31. It seems random to me, timing perhaps, still no idea. I've added template for Fedora 31, even though the problem is still there.

**Comment by aither64** [comment]
While working on an image for F33, I discovered that this can be solved by... disabling sshd.service. There's still sshd.socket, which seems to work reliably.

```
systemctl disable sshd.service
systemctl enable sshd.socket
```

(both are enabled by default, which somehow results in sshd sometimes not being started)

**Comment by GoodMirek** [comment]
Thanks!
Let me just share my finding which I forgot to add here - when sshd service was failing at boot, it printed to the console that it could not start as network was down. So there was/is probably a missing dependency somewhere.

**Comment by aither64** [comment]
Ah, I never noticed it. Well, it would definitely be better to have sshd.service enabled and functional, socket-activated ssh sucks when you're running out of memory, etc.
