### ISSUE TITLE
Add Red Hat Enterprise Linux images

### ISSUE THREAD

**Issue by ondra05** [vpsfreecz/vpsadminos-image-build-scripts#43]
From the 01/Feb/2020, RHEL will be for free for 16 devices for "small production workloads". [Link](https://www.redhat.com/en/blog/new-year-new-red-hat-enterprise-linux-programs-easier-ways-access-rhel)

So it would be nice to have RHEL 8 template for using.

**Comment by snajpa** [comment]
It certainly would *not* be nice. RHEL is not free software and what they have just showed us is a perfect example of "embrace-extend-extinguish", which should not be tolerated by anybody, much less by open community, such as vpsFree.cz.
