### ISSUE TITLE
GPG check failed

### ISSUE THREAD

**Issue by Cakebakery** [vpsfreecz/vpsadminos-image-build-scripts#46]
Use clean CentOS 9 Stream installation.
run command:
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm

to install the latest epel, unfortunately installation fails with message
"Key import failed (code 2). Failing package is: epel-next-release-9-2.el9.noarch"

**Comment by aither64** [comment]
Per their (https://docs.fedoraproject.org/en-US/epel/#_el9)[docs], you're supposed to run:

```
dnf config-manager --set-enabled crb
dnf install \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
    https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-9.noarch.rpm
```

I just tried it and it works.

**Comment by Cakebakery** [comment]
Thanks and sorry for false reporting.
